<?php

/**
 * @file
 * This is my module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
 function custom_footer_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Add a checkbox to site information form about configuring footer.
  $config = \Drupal::config('custom_footer.settings');

  $form['footer_visibility']= array(
    '#type' => 'checkbox',
    '#title' => t("Do you want to configure footer?"),
    '#default_value' => $config->get('footer_visibility'),
    '#weight'=> 99,

  );
  $form['siteinfo_footer_setting'] = array(
    '#type' => 'text_format',
    '#title' => t('Footer Configuration'),
    '#default_value' => $config->get('siteinfo_footer_setting'),
    '#states' => array(
      'visible' => array(
        ':input[name="footer_visibility"]' => array('checked' => TRUE),
      ),
    ),
  );
  $form['#submit'][] = 'custom_footer_form_system_site_information_settings_submit';
}

/**
 * Submit callback for system_site_information_form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
 function custom_footer_form_system_site_information_settings_submit(&$form, $form_state) {
   $config = \Drupal::service('config.factory')->getEditable('custom_footer.settings');
   $footer_message = $form_state->getValue('siteinfo_footer_setting');
   $config->set('siteinfo_footer_setting', $footer_message['value'])
     ->set('footer_visibility', $form_state->getValue('footer_visibility'))
     ->save();
}

?>
